#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
stoppingPoint = 4000000
i = 0
i2 =0
i3 = 1
summation = 0

while i3 < stoppingPoint:
    if i3%2 == 0:
        summation += i3
    i = i2
    i2 = i3
    i3 += i2 + i
print summation
    
    
    
    
